name: CarpetPlugin
version: "${projectVersion}"
main: carpet.CarpetPlugin
api-version: "1.21"
authors: [gnembon, leafcarpet]
description: Carpet Mod ported to Leaf
website: https://github.com/easy-k03/leafcarpet
load: STARTUP
folia-supported: false
softdepend:
  - ProtocolLib
  - packetevents
